[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ALWAYS"
healthcheckPath = "/health"
healthcheckTimeout = 300
numReplicas = 1  # Must be 1 since volumes don't support replicas

[[ports]]
port = "21115"
protocol = "tcp"

[[ports]]
port = "21116"
protocol = "tcp"

[[ports]]
port = "21116"
protocol = "udp"

[[ports]]
port = "21117"
protocol = "tcp"

[[ports]]
port = "21118"
protocol = "tcp"

[[ports]]
port = "21119"
protocol = "tcp"

[[volume]]
source = "rustdesk-server"
target = "/data"