[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ALWAYS"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[ports]]
port = "21115"
protocol = "tcp"

[[ports]]
port = "21116"
protocol = "tcp"

[[ports]]
port = "21116"
protocol = "udp"

[[ports]]
port = "21117"
protocol = "tcp"

[[ports]]
port = "21118"
protocol = "tcp"

[[ports]]
port = "21119"
protocol = "tcp"