[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ALWAYS"
numReplicas = 1

[env]
HBBR_SERVICE = "${{Linked.HBBR.RAILWAY_SERVICE_DOMAIN}}"

# Configuration for HBBR service
[services.hbbr]
startCommand = "sh -c 'hbbr'"

[[services.hbbr.ports]]
port = "21117"
protocol = "tcp"

[[services.hbbr.ports]]
port = "21119"
protocol = "tcp"

# Configuration for HBBS service
[services.hbbs]
startCommand = "sh -c 'hbbs -r ${HBBR_SERVICE}:21117'"
depends_on = ["hbbr"]

[[services.hbbs.ports]]
port = "21115"
protocol = "tcp"

[[services.hbbs.ports]]
port = "21116"
protocol = "tcp"

[[services.hbbs.ports]]
port = "21116"
protocol = "udp"

[[services.hbbs.ports]]
port = "21118"
protocol = "tcp"