[build]
builder = "DOCKERFILE"
dockerfilePath = "/HBBS/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[[ports]]
port = "21115"
protocol = "tcp"

[[ports]]
port = "21116"
protocol = "tcp"

[[ports]]
port = "21116"
protocol = "udp"

[[ports]]
port = "21118"
protocol = "tcp"

[[volume]]
source = "rustdesk-hbbs-data"
target = "/data"

[variables]
RELAY_SERVER = "rustdesk-hbbr.railway.internal"